# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="bira"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

#Source AWS keys
export AWS_PROFILE=default

aws_prod() {
  export AWS_PROFILE=prod
}

login_ecr() {
  eval $(aws ecr get-login --no-include-email --region eu-west-1)
}

minik() {
  minikube docker-env
  eval $(minikube docker-env)
}

# Set VIM as default editor
export EDITOR=vim

# Load ssh passphrase
eval $(ssh-agent -s)
ssh-add -t 28800 -K $HOME/.ssh/id_rsa

#Locale usually required by python
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#PATH
PATH=${PATH}:/usr/local/bin
PATH=${PATH}:/usr/local/sbin
PATH=${PATH}:/usr/local/git/bin
PATH=${PATH}:/usr/bin
PATH=${PATH}:/usr/sbin
PATH=${PATH}:/sbin
PATH=${PATH}:$HOME/packer
#Did explore like this so Brew can overwrite apple dev tool
export PATH="/usr/local/bin:$PATH"
