# Accept apps installed manually
homebrew_cask_accept_external_apps: true

dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Keynote
  - Numbers
  - Pages

dockitems_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: Slack
    path: "/Applications/Slack.app/"
    pos: 2
  - name: iTerm
    path: "/Applications/iTerm.app/"
    pos: 3
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app/"
    pos: 4
  - name: 1Password
    path: "/Applications/1Password.app/"
    pos: 5
  - name: Notion
    path: "/Applications/Notion.app/"
    pos: 6
  - name: Spotify
    path: "/Applications/Spotify.app/"
    pos: 7
