---
- name: "Inject laptop with caffeine"
  shell: "nohup caffeinate -t 1800 &"

- name: "Install cli packages"
  community.general.homebrew:
    name: "{{ cli_packages }}"
    update_homebrew: true
    upgrade_all: true
    state: present
  tags: ["cli_packages"]

#Homebrew community cask don't work very well: https://github.com/ansible-collections/community.general/issues/864
- name: "Install cask packages"
  homebrew_cask:
    name: "{{ app_packages }}"
  tags: ["mac_apps"]

- name: Set trackpad touch
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: true
    state: present
  tags: ["mac_configurations"]
